### ISSUE TITLE
Example on how to define a custom panel in Python. 

### ISSUE THREAD

**Issue by kaushik-keysight** [opentap/OpenTap.Python#105]
Is it possible to extend Editor UI using python as we do in C# dockable panels?

**Comment by rmadsen-ks** [comment]
It is definitely possible, but also probably quite hard. I don't think it is easy to write WPF code in python, but it would not be the supported way of doing it. 

At that point, I'd suggest writing it in C# instead. I am not sure I agree that this is an example we should have.

**Comment by rmadsen-ks** [comment]
This will not be fixed.
