### ISSUE TITLE
Broken link on README.md

### ISSUE THREAD

**Issue by g-galante** [opentap/OpenTap.Python#126]
The link to https://github.com/rmadsen-ks/pythonnet on commit b7497e8 is broken, because it seems that the repository has been renamed to https://github.com/rmadsen-ks/pythonnet_2.
If that is the case and you agree, I can volunteer to submit a PR to fix it.

**Comment by rmadsen-ks** [comment]
Hi @g-galante, thanks for noticing. I had not noticed because I had a private repo with that name.

Anyway, have renamed the projects so now the links should work.

Can you verify and close this issue?

**Comment by g-galante** [comment]
Sure
