### ISSUE TITLE
Tap commands does not work while Python and PythonExamples packages are installed

### ISSUE THREAD

**Issue by Razvan-Muresan** [opentap/OpenTap.Python#129]
When the Python and PythonExamples packages are installed on macOS (14.0), every time when a `./tap` command is executed this message is displayed in the terminal 
![image](https://github.com/opentap/OpenTap.Python/assets/132340651/6d5a3187-6207-430f-a16c-21194c6af80f)

Have to mention that I have Python 3.9.6 installed

Step to reproduce:
1. Install Python package (version 3.0.2+616d71b3)
2. Install PythonExamples package (version 3.0.2+616d71b3)
3. Run a `./tap` command, for example `./tap package list -i` 

I could reproduce this issue when both packages were installed. 
Also I attach here the verbose log
[Logs.pdf](https://github.com/opentap/OpenTap.Python/files/12790813/Logs.pdf)

**Comment by rmadsen-ks** [comment]
This works with 3.1.
