### ISSUE TITLE
Stray documentation from v2.x

### ISSUE THREAD

**Issue by g-galante** [opentap/OpenTap.Python#144]
Remove:
* [Documentation/TAP_Python_Help/Development_Process_Overview.md](https://github.com/opentap/OpenTap.Python/blob/5355d7b01959f2c1235b90c8550c91be5e754c0a/Documentation/TAP_Python_Help/Development_Process_Overview.md)
* [Documentation/TAP_Python_Help/Virtual_Environments.md](https://github.com/opentap/OpenTap.Python/blob/5355d7b01959f2c1235b90c8550c91be5e754c0a/Documentation/TAP_Python_Help/Virtual_Environments.md)

that are no longer referenced in: https://github.com/opentap/OpenTap.Python/blob/5355d7b01959f2c1235b90c8550c91be5e754c0a/Documentation/.vuepress/config.js#L15-L38

The only remaining reference to them:
```shell
~/git/OpenTap.Python$ git grep -E 'Development_Process_Overview.md|Virtual_Environments.md'
Documentation/TAP_Python_Help/Index.md:- [Python Development Process Overview](Development_Process_Overview.md)
```
is in [Documentation/TAP_Python_Help/Index.md](https://github.com/opentap/OpenTap.Python/blob/5355d7b01959f2c1235b90c8550c91be5e754c0a/Documentation/TAP_Python_Help/Index.md), which may be updated and renamed to `Readme.md`, so that it can by used by GitHub to provide an overview of the [Documentation/TAP_Python_Help/](https://github.com/opentap/OpenTap.Python/blob/5355d7b01959f2c1235b90c8550c91be5e754c0a/Documentation/TAP_Python_Help) folder content, and linked to by: https://github.com/opentap/OpenTap.Python/blob/5355d7b01959f2c1235b90c8550c91be5e754c0a/Documentation/Readme.md?plain=1#L23

**Comment by rmadsen-ks** [comment]
The virtual environments documentation was fixed in 3.2.
