### ISSUE TITLE
Create some additional examples

### ISSUE THREAD

**Issue by bdirenzo-keysight** [opentap/OpenTap.Python#39]
- Calling an existing Python script   
- Using PyVISA and PyVISA-py

**Comment by rmadsen-ks** [comment]
Maybe instead of the second option we can have an example of using ScpiInstrument? PyVisa is not really an option that we can support easily.

**Comment by bdirenzo-keysight** [comment]
@rmadsen-ks yes, ScpiInstrument would be a good start. @alan-copeland-keysight has done some work on the PyVISA side though. He was also one of the people struggling with the examples, so he may have additional ideas on what would be useful examples.

**Comment by rmadsen-ks** [comment]
An example was added using ScpiInstrument.
