### ISSUE TITLE
Validation rules don't work

### ISSUE THREAD

**Issue by SeltsamGestreifterOktopus** [opentap/OpenTap.Python#90]
Validation rules which are added in a test step which is written in Python are never evaluated.

The `PythonExamples` package contains a test step which contains rules (`BasicFunctionality.py`). Opening this step in the Editor (Community Edition) and changing the frequency to a negative number should trigger the red marker which indicates an illegal value, but this does not happen.

I added print statements to the constructor of the `Rule` class in `opentap.py` as well as to the method `Error()`. When the step is added, the constructor is called, but when I change the value of the frequency, the method is not called.

**Comment by rmadsen-ks** [comment]
Hi @SeltsamGestreifterOktopus, thanks for submitting the issue.

Sorry for the delay. I was able to verify and fix the issue. Will try to include it in the 3.0.2 release.
