### ISSUE TITLE
Python plugin hijacks CancelKeyPress

### ISSUE THREAD

**Issue by Denrask** [opentap/OpenTap.Python#92]
If I have Python plugin installed in my OpenTAP installation, then CTRL+C never triggers ICliAction cancellation.

```csharp
namespace PythonHijacksMyProject
{
    [Display("python", Group: "ownedby", Description: "Insert description here")]
    public class MyCliAction : ICliAction
    {
        public int Execute(CancellationToken cancellationToken)
        {
            while (!cancellationToken.IsCancellationRequested)
                Thread.Sleep(250);

            return 0;
        }
    }
}
```

Without Python installed, CTRL+C as expected hits the "return 0" line. With Python installed, nothing happens when pressing CTRL+C.

Additional notes:
- If Python is installed, deleting "OpenTap.Python.dll" is enough to fix this, so the problem is isolated to this dll.
- 🐴

**Comment by rmadsen-ks** [comment]
Hi @Denrask, which version of the plugin are you using?

**Comment by rmadsen-ks** [comment]
Ok, I can verify this behavior. It was fixed in the past, but somehow this turns out to cause problems again.

Related: https://github.com/pythonnet/pythonnet/pull/777

The behavior with regards to init sigs seems to be correct, so it must be something else.

**Comment by Denrask** [comment]
Thank you, @rmadsen-ks !
