### ISSUE TITLE
Generated Python project references "Readme.md" in package.xml, but file is actually "README.md". 

### ISSUE THREAD

**Issue by alan-copeland-keysight** [opentap/OpenTap.Python#98]
This causes package build issues on Linux / MacOS (case-sensitivity); this is most obvious when trying to package a plugin a Ubuntu runner in a Github action.

Recommendation is to fix case sensitivity to README.md in package.xml.

**Comment by rmadsen-ks** [comment]
This was fixed by: https://github.com/opentap/OpenTap.Python/commit/ed7c3682b484f74a7251da931573b1cf3789c314
